[package]
name = "oxilangtag"
version = "0.1.2"
authors = [
    "Tpt <thomas@pellissier-tanon.fr>"
]
license = "MIT"
readme = "README.md"
keywords = ["language-tag", "BCP47"]
repository = "https://github.com/oxigraph/oxilangtag"
description = """
Simple and fast implementation of language tag normalization and validation
"""
edition = "2018"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "lib"
harness = false
